# Form implementation generated from reading ui file './mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("* {\n"
"    background-color: rgb(30, 31, 34);\n"
"}\n"
"\n"
"QMenu#menuFile {\n"
"    color: rgb(238, 238, 236);\n"
"}\n"
"\n"
"QFrame#CompBrowserFrm{\n"
"    background-color: rgb(43, 45, 48);\n"
"}\n"
"\n"
"QFrame#ProjectViewerFrm {\n"
"    background-color: rgb(43, 45, 48);\n"
"}\n"
"\n"
"QFrame#ConsoleFrm {\n"
"    background-color: rgb(43, 45, 48);\n"
"}\n"
"\n"
"QFrame#PropertyEditorFrm {\n"
"    background-color: rgb(43, 45, 48);\n"
"}\n"
"\n"
"QFrame#NodeEditorFrm {\n"
"    background-color: rgb(43, 45, 48);\n"
"}\n"
"\n"
"QGraphicsView#NodeEditorView {\n"
"    background-color: rgb(63, 65, 68);\n"
"}\n"
"\n"
"QLineEdit#ConsoleEdit {\n"
"    background-color: rgb(250, 252, 255);\n"
"}\n"
"\n"
"Line#CompBrowserLine {\n"
"    \n"
"    border-color: rgb(238, 238, 236);\n"
"    background-color: rgb(238, 238, 236);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, -1)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.CompBrowserFrm = QtWidgets.QFrame(parent=self.centralwidget)
        self.CompBrowserFrm.setMaximumSize(QtCore.QSize(500, 16777215))
        self.CompBrowserFrm.setStyleSheet("")
        self.CompBrowserFrm.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.CompBrowserFrm.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.CompBrowserFrm.setObjectName("CompBrowserFrm")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.CompBrowserFrm)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.CompBrowserTreeView = UiCompBrowserTreeView(parent=self.CompBrowserFrm)
        self.CompBrowserTreeView.setObjectName("CompBrowserTreeView")
        self.gridLayout_4.addWidget(self.CompBrowserTreeView, 0, 0, 1, 1)
        self.CompBrowserView = UiCompBrowserView(parent=self.CompBrowserFrm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CompBrowserView.sizePolicy().hasHeightForWidth())
        self.CompBrowserView.setSizePolicy(sizePolicy)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        self.CompBrowserView.setBackgroundBrush(brush)
        self.CompBrowserView.setObjectName("CompBrowserView")
        self.gridLayout_4.addWidget(self.CompBrowserView, 2, 0, 1, 1)
        self.CompBrowserLine = QtWidgets.QFrame(parent=self.CompBrowserFrm)
        self.CompBrowserLine.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.CompBrowserLine.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.CompBrowserLine.setObjectName("CompBrowserLine")
        self.gridLayout_4.addWidget(self.CompBrowserLine, 1, 0, 1, 1)
        self.gridLayout_4.setRowStretch(0, 1)
        self.gridLayout_4.setRowStretch(2, 1)
        self.gridLayout.addWidget(self.CompBrowserFrm, 0, 0, 1, 1)
        self.NodeEditorFrm = QtWidgets.QFrame(parent=self.centralwidget)
        self.NodeEditorFrm.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.NodeEditorFrm.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.NodeEditorFrm.setObjectName("NodeEditorFrm")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.NodeEditorFrm)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.NodeEditorView = UiNodeEditorView(parent=self.NodeEditorFrm)
        self.NodeEditorView.setRenderHints(QtGui.QPainter.RenderHint.Antialiasing|QtGui.QPainter.RenderHint.TextAntialiasing)
        self.NodeEditorView.setViewportUpdateMode(QtWidgets.QGraphicsView.ViewportUpdateMode.FullViewportUpdate)
        self.NodeEditorView.setObjectName("NodeEditorView")
        self.gridLayout_2.addWidget(self.NodeEditorView, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.NodeEditorFrm, 0, 1, 1, 1)
        self.PropertyEditorFrm = QtWidgets.QFrame(parent=self.centralwidget)
        self.PropertyEditorFrm.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.PropertyEditorFrm.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.PropertyEditorFrm.setObjectName("PropertyEditorFrm")
        self.gridLayout.addWidget(self.PropertyEditorFrm, 0, 2, 2, 1)
        self.ProjectViewerFrm = QtWidgets.QFrame(parent=self.centralwidget)
        self.ProjectViewerFrm.setMaximumSize(QtCore.QSize(500, 16777215))
        self.ProjectViewerFrm.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.ProjectViewerFrm.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.ProjectViewerFrm.setObjectName("ProjectViewerFrm")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.ProjectViewerFrm)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.ProjectView = UiProjectTreeView(parent=self.ProjectViewerFrm)
        self.ProjectView.setObjectName("ProjectView")
        self.gridLayout_5.addWidget(self.ProjectView, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.ProjectViewerFrm, 1, 0, 1, 1)
        self.ConsoleFrm = QtWidgets.QFrame(parent=self.centralwidget)
        self.ConsoleFrm.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.ConsoleFrm.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.ConsoleFrm.setObjectName("ConsoleFrm")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ConsoleFrm)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ConsoleEdit = QtWidgets.QLineEdit(parent=self.ConsoleFrm)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ConsoleEdit.setFont(font)
        self.ConsoleEdit.setMaxLength(128)
        self.ConsoleEdit.setFrame(True)
        self.ConsoleEdit.setObjectName("ConsoleEdit")
        self.gridLayout_3.addWidget(self.ConsoleEdit, 1, 0, 1, 1)
        self.ConsoleBrowser = UiConsoleTextBrowser(parent=self.ConsoleFrm)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ConsoleBrowser.setFont(font)
        self.ConsoleBrowser.setObjectName("ConsoleBrowser")
        self.gridLayout_3.addWidget(self.ConsoleBrowser, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.ConsoleFrm, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 3)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setRowStretch(0, 2)
        self.gridLayout.setRowStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.menubar.setFont(font)
        self.menubar.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(parent=self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(parent=MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "Open File"))
from frontend.ui.comp_browser_treeview import UiCompBrowserTreeView
from frontend.ui.comp_browser_view import UiCompBrowserView
from frontend.ui.console_text_browser import UiConsoleTextBrowser
from frontend.ui.node_editor_view import UiNodeEditorView
from frontend.ui.ui_project_treeview import UiProjectTreeView
